title = "TOML FILE"

[root]
size = 20
max = 10000000 

[home]
dirs = 113
files = 18782631
permissions = "root"

[bin]
[bin.execute]
size = 100
files.names = [ "ls", "rm", "cat" ]
files.permissions = [ "rd", "rdrw", "rd" ]
files.owner = [ "root", "root", "root" ]
[bin.properties]
open = false
writable = true
readable = false
