title = "TOML Example"
physical.color = "orange"
physical.shape1 = "round1"
physical.shape2 = "round2"
physical."shape3" = "round3"
psychic.power = "mental"
xo = 192929
horas = 12:54:12
pp = ""

[owner]
name = "Tom Preston-Werner"
physical.color = "orange"
physical.shape1 = "round1"
physical.shape2 = "round2"
physical.shape3 = "round3"
psychic.power = "mental"
time = 21:30:00

[database]
server = "192.168.1.1"
ports = [ 8001, [8001,[11111,22222,33333] ]]
connection_max = 5000
enabled = true

[servers]
[servers.alpha]
  ip = "10.0.0.1"
  dc = "eqdc10"
physical.color = "orange"
physical.shape1 = "round1"
physical.shape2 = "round2"
physical.shape3 = "round3"
psychic.power = "mental"
dc2 = "eqdc10"

[servers.alpha.apha2]
physical.color = "orange"
physical.shape1 = "round1"
physical.shape2 = "round2"
physical.shape3 = "round3"
psychic.power = "mental"

[servers.beta]
  ip = "10.0.0.2"
  dc = "eqdc10"

[banan]
x = 1010
